### ISSUE TITLE
AppLock builder not updating state

### ISSUE THREAD

**Issue by digibum** [tomalabaster/flutter_app_lock#4] opened 2020-04-06 09:11 UTC
I have two pages (loginScreen and appHomeScreen) that AppLock should show based on user authentication status (isAuthenticated). This all works. But when user signs out, isAuthenticated changes to false and the AppLock should update to show loginScreen but it does not. What am I dooing wrong? IsAuthenticated gets set by EventBus that is emitted by the authprovider.

```
void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool isAuthenticated = false;
  bool requiresPasscode = false;

  @override
  void initState() {
    super.initState();
    startupProviders();
    eventBus.on<OnUserLogOut>().listen((event) => onUserLogOut(event));
    i18n.onLocaleChangedCallback = _onStateChanged;
  }

  @override
  void dispose() {
    super.dispose();
  }

  startupProviders() async {
    await i18n.init();
    await auth.init();
    isAuthenticated = await auth.isAuthenticated();
    requiresPasscode = await auth.isPasscodeEnabled();
    setState(() {});
  }

  onUserLogOut(OnUserLogOut event) {
    setState(() {
      isAuthenticated = false;
      requiresPasscode = false;
    });
  }

  // Main initialization
  @override
  Widget build(BuildContext context) {
    return DynamicTheme(
        defaultBrightness: Brightness.light,
        data: (brightness) => ThemeData(
              primarySwatch: Colors.brown,
              brightness: brightness,
            ),
        themedWidgetBuilder: (context, theme) {
          return MaterialApp(
              localizationsDelegates: [
                GlobalMaterialLocalizations.delegate,
                GlobalWidgetsLocalizations.delegate,
              ],
              supportedLocales: i18n.supportedLocales(),
              theme: theme,
              home: AppLock(
                builder: (context) =>
                    isAuthenticated ? AppHomeScreen() : LoginScreen(),
                lockScreen: PassCodeScreen(),
                enabled: requiresPasscode,
              ));
        });
  }
}

```

**Comment by tomalabaster** [comment] 2020-05-14 09:26
Interesting use case. I built this imagining it to be used as the top most widget in the tree as oppose to lower in the tree but I can see why it is needed.

I'll give it some thought as to the best way to handle this, as I suspect simply updating enabled based on the `didUpdateWidget` could lead to some unexpected behaviour for some. Potentially requiring a callback for when `enabled` changes internally could allow for AppLock to maintain its own state but also help other widgets keeping track as well for use cases like this.

**Comment by tomalabaster** [comment] 2020-05-16 10:31
I understand what you're trying to achieve but the async operations aren't going to work here. Because the `build` method will get called once anyway before `startupProviders` has finished, `build` will build `AppLock` with the `builder` method set to return the `LoginScreen`.

What you should really do is change the widget given to`runApp` to be `AppLock` like below, `MyApp` widget to take in the `isAuthenticated` property and decide whether or not to show the `LoginScreen` or `HomeScreen` as its `home`.

You can then use the available `enable`, `disable` and `showLockScreen` methods available using `AppLock.of(context)` to control when your `PassCodeScreen` should be shown.

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // only needed if the auth object in the lines below uses method channels

  final isAuthenticated = await auth.isAuthenticated();
  final requiresPasscode = await auth.isPasscodeEnabled();

  runApp(AppLock(
    builder: (args) => MyApp(
      data: args,
      isAuthenticated: isAuthenticated,
    ),
    lockScreen: PassCodeScreen(),
    enabled: requiresPasscode,
  ));
}
```

I hope this helps. I've given it some thought and I do still think that `AppLock` should be the top  (or at least one of the top) most widgets and you can still achieve what you want by doing this.

I'll leave this open for now, if you still disagree then do reply otherwise I'll close this issue.

**Comment by PolymathWhiz** [comment] 2020-05-18 19:57
Interesting fix. Solved my issue too

**Comment by tomalabaster** [comment] 2020-05-20 20:27
After careful consideration I think it is still beneficial to not update the state upon widget changing in order to avoid unexpected behaviour. I'm happy to be shown a use case in the future which shows otherwise though.

`AppLock` should still be one of the top most widgets in the tree.

**Closed by tomalabaster** 2020-05-20 20:27 UTC
